base/urls.py
from django.urls import path, include

from base import views

app_name = 'base'
urlpatterns = [
    #path('api/base/', include(router.urls)),
    path('', views.encuesta_lista, name='encuestas'),
    path('anteriores', views.encuesta_pasada, name='encuestas_pasadas'),
    path('encuesta/<int:id>', views.encuesta, name='encuesta'),
    path('resultado/<int:id>', views.resultado, name='resultado'),
    path('registrar', views.registrar, name='registrar'),
]

encuestas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

admin.site.site_header = "Encuestas Admin"
admin.site.site_title = "Encuestas Admin Portal"
admin.site.index_title = "Bienvenido a las encuestas"

base/models.py
from django.db import models


class Encuesta(models.Model):
    titulo = models.CharField(max_length=255)
    vencimiento = models.DateTimeField(null=True, blank=True)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.titulo


class Opcion(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    opcion = models.CharField(max_length=255)
    votos = models.IntegerField(default=0)


class Ip(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    ip = models.CharField(max_length=255)

base/views.py
from django.shortcuts import render, get_object_or_404
from django.http.response import HttpResponseRedirect
from django.urls import reverse

from django.utils import timezone

from base.models import Encuesta, Opcion, Ip
from base.utils import ip_cliente

def encuesta_lista(request):
    encuestas = Encuesta.objects.filter(activo=True)
    context = {
        'encuestas': encuestas
    }
    return render(request, 'base/encuesta-lista.html', context)

def encuesta_pasada(request):
    now = timezone.now()
    encuestas = Encuesta.objects.filter(vencimiento__lte=now)

    context = {
        'encuestas': encuestas
    }
    return render(request, 'base/encuesta-lista.html', context)

def encuesta(request, id):
    encuesta = Encuesta.objects.get(id=id)

    now = timezone.now()
    vencimiento = encuesta.vencimiento

    tiempo_restante = vencimiento - now

    dias_restantes = tiempo_restante.days
    horas_restantes, segundos_restantes = divmod(tiempo_restante.seconds, 3600)
    minutos_restantes, _ = divmod(segundos_restantes, 60)

    tiempo_formateado = f"Vence en {dias_restantes} días, {horas_restantes} horas y {minutos_restantes} minutos."

    vencido = now > vencimiento

    if not request.user.is_authenticated:
        ip = ip_cliente(request)
        ya_voto = Ip.objects.filter(ip=ip, encuesta=encuesta).count()
        if ya_voto > 0:
            return HttpResponseRedirect(reverse('base:resultado', args=[encuesta.pk]))

    context = {
        'encuesta': encuesta,
        'tiempo': tiempo_formateado,
        'vencido': vencido
    }
    if vencido:
        return render(request, 'base/resultado.html', context)
    else:
        return render(request, 'base/encuesta.html', context)

def registrar(request):
    opcion = Opcion.objects.get(pk=request.POST.get('opcion'))
    opcion.votos = opcion.votos+1
    opcion.save()

    if not request.user.is_authenticated:
        ip = ip_cliente(request)
        contador_ip = Ip.objects.filter(ip=ip).count()
        if contador_ip == 0:
            nuevo_ip = Ip(encuesta=opcion.encuesta, ip=ip)
            nuevo_ip.save()

    return HttpResponseRedirect(reverse('base:resultado', args=[opcion.encuesta.pk]))

def resultado(request, id):
    encuesta = Encuesta.objects.get(id=id)
    context = {
        'encuesta': encuesta
    }
    return render(request, 'base/resultado.html', context)

base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Encuestas - {% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% block css %}
    {% endblock css %}        
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary"  data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'base:encuestas' %}">Encuestas Lincoln</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'base:encuestas' %}">Encuestas actuales</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'base:encuestas_pasadas' %}">Encuestas pasadas</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        {% block main %} 
        {% endblock main %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock js %}
</body>
</html>

base/templates/base/encuesta-lista.html
{% extends 'base/base.html' %}


{% block main %}
    <h1>Bienvenido a las encuestas</h1>


    <p>Escoge una encuesta para votar</p>
    <ul>
        {% for encuesta in encuestas%}
        <li>
            <a href="{% url "base:encuesta" encuesta.id %}">{{ encuesta.titulo }}</a>
            (Vence el {{ encuesta.vencimiento|date:"d M Y" }})
        </li>
        {% endfor %}
    </ul>    
{% endblock main %}


{% block title %}
    Lista de encuestas
{% endblock title %}

base/templates/base/encuesta.html
{% extends 'base/base.html' %}

{% block main %}
    <h1>{{ encuesta.titulo }}</h1>
    <p>{{ tiempo }}</p>

    <form action="{% url 'base:registrar' %}" method="post">
        <ul class="list-unstyled">
            {% for opcion in encuesta.opcion_set.all %}
                <li>
                    <input required type="radio" name="opcion" id="opcion-{{opcion.id}}" value="{{opcion.id}}">
                    <label for="opcion-{{opcion.id}}">{{ opcion.opcion }}</label>
                </li>
            {% endfor %}
        </ul>

        <div class="text-center">
            <button class="btn btn-primary">Votar</button>
            <a class="btn btn-success" href="{% url 'base:resultado' encuesta.id %}">Ver resultados</a>
        </div>
        {% csrf_token %}
    </form>
{% endblock main %}


{% block title %}
    {{ encuesta.titulo }}
{% endblock title %}
    

base/templates/base/resultado.html
{% extends 'base/base.html' %}

{% block main %}
    <h1 class="mb-5">{{ encuesta.titulo }}</h1>
    <div class="row">
        <div class="col"></div>
        <div class="col-md-6">
            <canvas id="myChart" style=""></canvas>
            <div class="text-center mt-5">
                <p><a href="{% url 'base:encuestas' %}" class="btn btn-primary">Regresar </a></p>
            </div>
        </div>
        <div class="col"></div>
    </div>

{% endblock main %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        {% spaceless %}
            var labels = []
            var data = []
            var total =
            {% for opcion in encuesta.opcion_set.all %}
                {{opcion.votos}} +
            {% endfor %}
            0;

            {% for opcion in encuesta.opcion_set.all %}
                labels.push('{{ opcion.opcion }}')
                data.push({{ opcion.votos }})
            {% endfor %}
            
        {% endspaceless %}
        const ctx = document.getElementById('myChart');


        new Chart(ctx, {
            type: 'pie',
            data: {
            labels: labels,
            datasets: [{
                label: 'Número de votos',
                data: data,
                borderWidth: 1
            }]
            },
        });

    </script>
{% endblock js %}


{% block title %}
    {{ encuesta.titulo }} - resultados
{% endblock title %}